# Generated by Django 4.2 on 2023-04-30 19:41

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=landing.models.photos_directory)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('second_price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
