# Generated by Django 4.2 on 2023-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='article',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='detail',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='second_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
